"""Verification Checklist (v1.0.0 Candidate Intelligence, Phase 8).

Deterministic rule table keyed on strongest_artifact_type, presence of
official documentation, contradiction findings, independent-confirmation
count, and entity resolution status -- never generated by an LLM. Each
rule is independent and additive; a candidate can trigger any number of
them. If nothing applies, that itself is reported explicitly rather than
returning an empty, ambiguous list.
"""

from __future__ import annotations

from dataclasses import dataclass

from sqlalchemy import select
from sqlalchemy.orm import Session

from semi_intel.domain.models import CandidateEntity, SignalCandidate
from semi_intel.signals.claims import Contradiction
from semi_intel.signals.confidence_engine import candidate_item_ids, official_documentation_component

ARTIFACT_VERIFICATION_STEPS: dict[str, str] = {
    "pci_id": "Cross-check the PCI/USB ID against the pci.ids or usb.ids registry",
    "benchmark": "Search Geekbench and other benchmark databases for a matching listing",
    "codename": "Compare against the prior-generation SKU/product for naming consistency",
    "product": "Compare against the prior-generation SKU/product for consistency",
    "version": "Confirm the version/revision number against official changelogs",
    "retailer": "Check retailer/product-catalog pages for a matching listing",
}


@dataclass
class VerificationStep:
    step: str
    reason: str

    def to_dict(self) -> dict:
        return {"step": self.step, "reason": self.reason}


def generate_verification_checklist(
    session: Session, candidate: SignalCandidate, contradictions: list[Contradiction],
) -> list[VerificationStep]:
    steps: list[VerificationStep] = []
    item_ids = candidate_item_ids(session, candidate)

    official_raw, _ = official_documentation_component(session, item_ids)
    if official_raw < 1.0:
        steps.append(VerificationStep(
            "Search OEM/vendor sites for an official announcement or support page",
            "No official documentation found among current evidence",
        ))

    if candidate.strongest_artifact_type in ARTIFACT_VERIFICATION_STEPS:
        steps.append(VerificationStep(
            ARTIFACT_VERIFICATION_STEPS[candidate.strongest_artifact_type],
            f"Strongest identified artifact type is {candidate.strongest_artifact_type!r}",
        ))

    for contradiction in contradictions:
        steps.append(VerificationStep(
            f"Resolve conflicting {contradiction.claim_type.replace('_', ' ')}: "
            "compare against an OEM listing or official spec sheet",
            contradiction.reason,
        ))

    if candidate.independent_source_group_count < 2:
        steps.append(VerificationStep(
            "Wait for or actively search for an independent confirmation",
            f"Only {candidate.independent_source_group_count} independent confirmation group(s) so far",
        ))

    has_resolved_entity = session.execute(
        select(CandidateEntity.id).where(CandidateEntity.candidate_id == candidate.id).limit(1)
    ).first()
    if not has_resolved_entity:
        steps.append(VerificationStep(
            "Identify and resolve the subject entity for this candidate",
            "No entity is currently linked to this candidate",
        ))

    if not steps:
        steps.append(VerificationStep(
            "No specific verification gaps identified from available evidence",
            "All deterministic checks (official documentation, structured artifact, "
            "contradictions, independent confirmation, entity resolution) passed",
        ))
    return steps
