"""signal topic matches

Revision ID: 4ee15190b40b
Revises: f4f0279f3459
Create Date: 2026-07-26 14:58:15.706147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ee15190b40b'
down_revision: Union[str, Sequence[str], None] = 'f4f0279f3459'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signal_topic_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_item_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('matched_text', sa.String(length=255), nullable=False),
    sa.Column('processing_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['signal_item_id'], ['signal_items.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['monitored_topics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signal_item_id', 'topic_id', name='uq_signal_topic_matches')
    )
    op.create_index(op.f('ix_signal_topic_matches_signal_item_id'), 'signal_topic_matches', ['signal_item_id'], unique=False)
    op.create_index(op.f('ix_signal_topic_matches_topic_id'), 'signal_topic_matches', ['topic_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signal_topic_matches_topic_id'), table_name='signal_topic_matches')
    op.drop_index(op.f('ix_signal_topic_matches_signal_item_id'), table_name='signal_topic_matches')
    op.drop_table('signal_topic_matches')
    # ### end Alembic commands ###
