"""initial schema

Revision ID: 71747eaa2044
Revises: 
Create Date: 2026-07-18 12:13:38.003734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71747eaa2044'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('PRODUCT', 'COMPANY', 'PERSON', 'ARCHITECTURE', 'FOUNDRY_NODE', 'PACKAGING_TECH', 'MEMORY_TECH', 'BENCHMARK', 'OTHER', name='entitytype'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('aliases', sa.Text(), nullable=False),
    sa.Column('attributes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entities_name'), 'entities', ['name'], unique=True)
    op.create_index(op.f('ix_entities_type'), 'entities', ['type'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('RSS', 'FORUM', 'SOCIAL', 'RETAIL', 'REGULATORY', 'KERNEL', 'REGISTRY', 'PATENT', 'MANUAL', 'OTHER', name='sourcetype'), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('trust_weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_name'), 'sources', ['name'], unique=True)
    op.create_table('claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('subject_entity_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'CONFIRMED', 'DEBUNKED', 'RETRACTED', name='claimstatus'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subject_entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_status'), 'claims', ['status'], unique=False)
    op.create_index(op.f('ix_claims_subject_entity_id'), 'claims', ['subject_entity_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('observed_at', sa.DateTime(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_content_hash'), 'evidence', ['content_hash'], unique=True)
    op.create_index(op.f('ix_evidence_entity_id'), 'evidence', ['entity_id'], unique=False)
    op.create_index(op.f('ix_evidence_external_id'), 'evidence', ['external_id'], unique=False)
    op.create_index(op.f('ix_evidence_source_id'), 'evidence', ['source_id'], unique=False)
    op.create_table('relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_entity_id', sa.Integer(), nullable=False),
    sa.Column('to_entity_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.Enum('MANUFACTURED_BY', 'USES_NODE', 'USES_PACKAGING', 'USES_MEMORY', 'SUCCESSOR_OF', 'PART_OF', 'COMPETES_WITH', 'RELATED_TO', name='relationtype'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['to_entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_entity_id', 'to_entity_id', 'relation_type')
    )
    op.create_index(op.f('ix_relationships_from_entity_id'), 'relationships', ['from_entity_id'], unique=False)
    op.create_index(op.f('ix_relationships_to_entity_id'), 'relationships', ['to_entity_id'], unique=False)
    op.create_table('claim_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('CREATED', 'EVIDENCE_LINKED', 'EVIDENCE_UNLINKED', 'CONFIDENCE_UPDATED', 'STATUS_CHANGED', 'CONTRADICTION_CHECK_PASSED', 'CONTRADICTION_DETECTED', name='claimeventtype'), nullable=False),
    sa.Column('confidence_after', sa.Float(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_events_claim_id'), 'claim_events', ['claim_id'], unique=False)
    op.create_table('claim_evidence_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('stance', sa.Enum('SUPPORTS', 'WEAKENS', 'CONTRADICTS', name='evidencestance'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_id', 'evidence_id')
    )
    op.create_index(op.f('ix_claim_evidence_links_claim_id'), 'claim_evidence_links', ['claim_id'], unique=False)
    op.create_index(op.f('ix_claim_evidence_links_evidence_id'), 'claim_evidence_links', ['evidence_id'], unique=False)
    op.create_table('claim_link_suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('reasons', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='suggestionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evidence_id', 'claim_id')
    )
    op.create_index(op.f('ix_claim_link_suggestions_claim_id'), 'claim_link_suggestions', ['claim_id'], unique=False)
    op.create_index(op.f('ix_claim_link_suggestions_evidence_id'), 'claim_link_suggestions', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_claim_link_suggestions_status'), 'claim_link_suggestions', ['status'], unique=False)
    op.create_table('memory_spec_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('memory_type', sa.String(length=50), nullable=True),
    sa.Column('bus_width_bits', sa.Integer(), nullable=False),
    sa.Column('chip_density_gbit', sa.Float(), nullable=False),
    sa.Column('claimed_total_gb', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_spec_claims_claim_id'), 'memory_spec_claims', ['claim_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memory_spec_claims_claim_id'), table_name='memory_spec_claims')
    op.drop_table('memory_spec_claims')
    op.drop_index(op.f('ix_claim_link_suggestions_status'), table_name='claim_link_suggestions')
    op.drop_index(op.f('ix_claim_link_suggestions_evidence_id'), table_name='claim_link_suggestions')
    op.drop_index(op.f('ix_claim_link_suggestions_claim_id'), table_name='claim_link_suggestions')
    op.drop_table('claim_link_suggestions')
    op.drop_index(op.f('ix_claim_evidence_links_evidence_id'), table_name='claim_evidence_links')
    op.drop_index(op.f('ix_claim_evidence_links_claim_id'), table_name='claim_evidence_links')
    op.drop_table('claim_evidence_links')
    op.drop_index(op.f('ix_claim_events_claim_id'), table_name='claim_events')
    op.drop_table('claim_events')
    op.drop_index(op.f('ix_relationships_to_entity_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_from_entity_id'), table_name='relationships')
    op.drop_table('relationships')
    op.drop_index(op.f('ix_evidence_source_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_external_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_entity_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_content_hash'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_claims_subject_entity_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_status'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_sources_name'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_entities_type'), table_name='entities')
    op.drop_index(op.f('ix_entities_name'), table_name='entities')
    op.drop_table('entities')
    # ### end Alembic commands ###
