"""candidate promotion audit

Revision ID: a6a1b2c73e08
Revises: 4ee15190b40b
Create Date: 2026-07-26 15:43:48.787608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6a1b2c73e08'
down_revision: Union[str, Sequence[str], None] = '4ee15190b40b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_promotion_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('promoted_by', sa.String(length=100), nullable=False),
    sa.Column('automatic', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['signal_candidates.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['editorial_stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_promotion_events_candidate_id'), 'candidate_promotion_events', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_promotion_events_created_at'), 'candidate_promotion_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_candidate_promotion_events_story_id'), 'candidate_promotion_events', ['story_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidate_promotion_events_story_id'), table_name='candidate_promotion_events')
    op.drop_index(op.f('ix_candidate_promotion_events_created_at'), table_name='candidate_promotion_events')
    op.drop_index(op.f('ix_candidate_promotion_events_candidate_id'), table_name='candidate_promotion_events')
    op.drop_table('candidate_promotion_events')
    # ### end Alembic commands ###
