"""candidate human QC review

Revision ID: bf599f950d56
Revises: a0b1c2d3e404
Create Date: 2026-08-27 13:29:31.964505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf599f950d56'
down_revision: Union[str, Sequence[str], None] = 'a0b1c2d3e404'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('candidate_title', sa.String(length=500), nullable=False),
    sa.Column('attention_score_at_review', sa.Float(), nullable=True),
    sa.Column('item_count_at_review', sa.Integer(), nullable=True),
    sa.Column('disposition', sa.Enum('USEFUL', 'NOT_USEFUL', 'FALSE_POSITIVE', 'DUPLICATE', name='candidatereviewdisposition'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('review_metadata', sa.Text(), nullable=False),
    sa.Column('is_corrected', sa.Boolean(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['signal_candidates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', name='uq_candidate_review_candidate_id')
    )
    op.create_index(op.f('ix_candidate_reviews_candidate_id'), 'candidate_reviews', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_reviews_disposition'), 'candidate_reviews', ['disposition'], unique=False)
    op.create_index(op.f('ix_candidate_reviews_reviewed_at'), 'candidate_reviews', ['reviewed_at'], unique=False)
    # NOTE: autogenerate also detected three pre-existing unique=False ->
    # unique=True index drifts (notification_digests.dedup_key,
    # notifications.dedup_key, provider_incidents.incident_key) unrelated
    # to this change -- an existing model/migration mismatch predating this
    # revision. Deliberately NOT included here to keep this migration
    # scoped to the candidate QC review table only; left for a separate,
    # dedicated fix.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidate_reviews_reviewed_at'), table_name='candidate_reviews')
    op.drop_index(op.f('ix_candidate_reviews_disposition'), table_name='candidate_reviews')
    op.drop_index(op.f('ix_candidate_reviews_candidate_id'), table_name='candidate_reviews')
    op.drop_table('candidate_reviews')
    # ### end Alembic commands ###
