"""signal radar absorption: signal layer

Revision ID: f4f0279f3459
Revises: b71d4e2c9a30
Create Date: 2026-07-26 14:22:55.072261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4f0279f3459'
down_revision: Union[str, Sequence[str], None] = 'b71d4e2c9a30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attention_scoring_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weight_topic_relevance', sa.Float(), nullable=False),
    sa.Column('weight_novelty', sa.Float(), nullable=False),
    sa.Column('weight_momentum', sa.Float(), nullable=False),
    sa.Column('weight_source_diversity', sa.Float(), nullable=False),
    sa.Column('weight_artifact_strength', sa.Float(), nullable=False),
    sa.Column('weight_source_quality', sa.Float(), nullable=False),
    sa.Column('momentum_window_hours', sa.Integer(), nullable=False),
    sa.Column('staleness_days', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate_promotion_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('automatic_promotion_enabled', sa.Boolean(), nullable=False),
    sa.Column('minimum_attention_score', sa.Float(), nullable=False),
    sa.Column('required_topic_match', sa.Boolean(), nullable=False),
    sa.Column('maximum_candidate_age_hours', sa.Integer(), nullable=False),
    sa.Column('hourly_promotion_budget', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signal_collection_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_enabled', sa.Boolean(), nullable=False),
    sa.Column('x_provider_enabled', sa.Boolean(), nullable=False),
    sa.Column('startup_stagger_seconds', sa.Integer(), nullable=False),
    sa.Column('media_download_enabled', sa.Boolean(), nullable=False),
    sa.Column('ocr_enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signal_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=500), nullable=False),
    sa.Column('raw_payload', sa.Text(), nullable=False),
    sa.Column('normalized_text', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('expanded_links', sa.Text(), nullable=False),
    sa.Column('author_handle', sa.String(length=255), nullable=True),
    sa.Column('author_display_name', sa.String(length=255), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('fidelity', sa.String(length=20), nullable=False),
    sa.Column('quoted_external_id', sa.String(length=500), nullable=True),
    sa.Column('quoted_signal_item_id', sa.Integer(), nullable=True),
    sa.Column('reply_to_external_id', sa.String(length=500), nullable=True),
    sa.Column('reply_to_signal_item_id', sa.Integer(), nullable=True),
    sa.Column('deleted_observed_at', sa.DateTime(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('processing_version', sa.Integer(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('processing_state', sa.Enum('PENDING', 'PROCESSED', 'FAILED', name='signalprocessingstate'), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('origin_evidence_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['origin_evidence_id'], ['evidence.id'], ),
    sa.ForeignKeyConstraint(['quoted_signal_item_id'], ['signal_items.id'], ),
    sa.ForeignKeyConstraint(['reply_to_signal_item_id'], ['signal_items.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_id', name='uq_signal_items_provider_external_id')
    )
    op.create_index(op.f('ix_signal_items_author_handle'), 'signal_items', ['author_handle'], unique=False)
    op.create_index(op.f('ix_signal_items_collected_at'), 'signal_items', ['collected_at'], unique=False)
    op.create_index(op.f('ix_signal_items_content_hash'), 'signal_items', ['content_hash'], unique=False)
    op.create_index(op.f('ix_signal_items_external_id'), 'signal_items', ['external_id'], unique=False)
    op.create_index(op.f('ix_signal_items_origin_evidence_id'), 'signal_items', ['origin_evidence_id'], unique=False)
    op.create_index(op.f('ix_signal_items_posted_at'), 'signal_items', ['posted_at'], unique=False)
    op.create_index(op.f('ix_signal_items_processing_state'), 'signal_items', ['processing_state'], unique=False)
    op.create_index(op.f('ix_signal_items_provider'), 'signal_items', ['provider'], unique=False)
    op.create_index(op.f('ix_signal_items_quoted_signal_item_id'), 'signal_items', ['quoted_signal_item_id'], unique=False)
    op.create_index(op.f('ix_signal_items_reply_to_signal_item_id'), 'signal_items', ['reply_to_signal_item_id'], unique=False)
    op.create_index(op.f('ix_signal_items_source_id'), 'signal_items', ['source_id'], unique=False)
    op.create_table('provider_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('items_collected', sa.Integer(), nullable=False),
    sa.Column('duplicates_skipped', sa.Integer(), nullable=False),
    sa.Column('cursor_before', sa.Text(), nullable=True),
    sa.Column('cursor_after', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'OK', 'PARTIAL', 'FAILED', name='providerrunstatus'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_runs_provider'), 'provider_runs', ['provider'], unique=False)
    op.create_index(op.f('ix_provider_runs_source_id'), 'provider_runs', ['source_id'], unique=False)
    op.create_index(op.f('ix_provider_runs_started_at'), 'provider_runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_provider_runs_status'), 'provider_runs', ['status'], unique=False)
    op.create_table('signal_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('state', sa.Enum('ACTIVE', 'PROMOTED', 'DISMISSED', 'SNOOZED', 'STALE', 'MERGED', name='signalcandidatestate'), nullable=False),
    sa.Column('attention_score', sa.Float(), nullable=False),
    sa.Column('score_explanation', sa.Text(), nullable=False),
    sa.Column('first_observed_at', sa.DateTime(), nullable=False),
    sa.Column('latest_observed_at', sa.DateTime(), nullable=False),
    sa.Column('momentum_window_seconds', sa.Integer(), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('distinct_source_count', sa.Integer(), nullable=False),
    sa.Column('independent_source_group_count', sa.Integer(), nullable=False),
    sa.Column('primary_topic_id', sa.Integer(), nullable=True),
    sa.Column('strongest_artifact_type', sa.String(length=50), nullable=True),
    sa.Column('likely_origin_signal_item_id', sa.Integer(), nullable=True),
    sa.Column('promoted_story_id', sa.Integer(), nullable=True),
    sa.Column('seen_at', sa.DateTime(), nullable=True),
    sa.Column('snoozed_until', sa.DateTime(), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(), nullable=True),
    sa.Column('dismissed_reason', sa.Text(), nullable=True),
    sa.Column('clustering_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['likely_origin_signal_item_id'], ['signal_items.id'], ),
    sa.ForeignKeyConstraint(['primary_topic_id'], ['monitored_topics.id'], ),
    sa.ForeignKeyConstraint(['promoted_story_id'], ['editorial_stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_candidates_attention_score'), 'signal_candidates', ['attention_score'], unique=False)
    op.create_index(op.f('ix_signal_candidates_created_at'), 'signal_candidates', ['created_at'], unique=False)
    op.create_index(op.f('ix_signal_candidates_fingerprint'), 'signal_candidates', ['fingerprint'], unique=True)
    op.create_index(op.f('ix_signal_candidates_first_observed_at'), 'signal_candidates', ['first_observed_at'], unique=False)
    op.create_index(op.f('ix_signal_candidates_latest_observed_at'), 'signal_candidates', ['latest_observed_at'], unique=False)
    op.create_index(op.f('ix_signal_candidates_likely_origin_signal_item_id'), 'signal_candidates', ['likely_origin_signal_item_id'], unique=False)
    op.create_index(op.f('ix_signal_candidates_primary_topic_id'), 'signal_candidates', ['primary_topic_id'], unique=False)
    op.create_index(op.f('ix_signal_candidates_promoted_story_id'), 'signal_candidates', ['promoted_story_id'], unique=False)
    op.create_index(op.f('ix_signal_candidates_seen_at'), 'signal_candidates', ['seen_at'], unique=False)
    op.create_index(op.f('ix_signal_candidates_snoozed_until'), 'signal_candidates', ['snoozed_until'], unique=False)
    op.create_index(op.f('ix_signal_candidates_state'), 'signal_candidates', ['state'], unique=False)
    op.create_table('signal_entity_mentions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_item_id', sa.Integer(), nullable=False),
    sa.Column('candidate_text', sa.String(length=500), nullable=False),
    sa.Column('proposed_entity_type', sa.String(length=30), nullable=False),
    sa.Column('resolved_entity_id', sa.Integer(), nullable=True),
    sa.Column('span_start', sa.Integer(), nullable=True),
    sa.Column('span_end', sa.Integer(), nullable=True),
    sa.Column('extractor', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('processing_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('RESOLVED', 'CANDIDATE', 'REJECTED', 'IGNORED', name='signalmentionstatus'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resolved_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['signal_item_id'], ['signal_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_entity_mentions_candidate_text'), 'signal_entity_mentions', ['candidate_text'], unique=False)
    op.create_index(op.f('ix_signal_entity_mentions_resolved_entity_id'), 'signal_entity_mentions', ['resolved_entity_id'], unique=False)
    op.create_index(op.f('ix_signal_entity_mentions_signal_item_id'), 'signal_entity_mentions', ['signal_item_id'], unique=False)
    op.create_index(op.f('ix_signal_entity_mentions_status'), 'signal_entity_mentions', ['status'], unique=False)
    op.create_table('signal_labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_item_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('rule', sa.String(length=200), nullable=False),
    sa.Column('processing_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['signal_item_id'], ['signal_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signal_item_id', 'label', name='uq_signal_labels_item_label')
    )
    op.create_index(op.f('ix_signal_labels_label'), 'signal_labels', ['label'], unique=False)
    op.create_index(op.f('ix_signal_labels_signal_item_id'), 'signal_labels', ['signal_item_id'], unique=False)
    op.create_table('signal_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_item_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('remote_url', sa.String(length=2048), nullable=False),
    sa.Column('alt_text', sa.Text(), nullable=True),
    sa.Column('from_quoted', sa.Boolean(), nullable=False),
    sa.Column('local_path', sa.String(length=1024), nullable=True),
    sa.Column('download_state', sa.Enum('PENDING', 'DOWNLOADED', 'FAILED', 'SKIPPED', name='signalmediadownloadstate'), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(), nullable=True),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('ocr_engine', sa.String(length=100), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['signal_item_id'], ['signal_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signal_item_id', 'remote_url', name='uq_signal_media_item_url')
    )
    op.create_index(op.f('ix_signal_media_download_state'), 'signal_media', ['download_state'], unique=False)
    op.create_index(op.f('ix_signal_media_signal_item_id'), 'signal_media', ['signal_item_id'], unique=False)
    op.create_table('candidate_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('SUBJECT', 'MENTIONED', name='candidateentityrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['signal_candidates.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'entity_id', name='uq_candidate_entities')
    )
    op.create_index(op.f('ix_candidate_entities_candidate_id'), 'candidate_entities', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_entities_entity_id'), 'candidate_entities', ['entity_id'], unique=False)
    op.create_table('candidate_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_candidate_id', sa.Integer(), nullable=False),
    sa.Column('to_candidate_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.Enum('MERGED_INTO', 'RELATED_TO', 'DUPLICATE_OF', name='candidaterelationtype'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_candidate_id'], ['signal_candidates.id'], ),
    sa.ForeignKeyConstraint(['to_candidate_id'], ['signal_candidates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_candidate_id', 'to_candidate_id', 'relation_type', name='uq_candidate_relationships')
    )
    op.create_index(op.f('ix_candidate_relationships_from_candidate_id'), 'candidate_relationships', ['from_candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_relationships_to_candidate_id'), 'candidate_relationships', ['to_candidate_id'], unique=False)
    op.create_table('candidate_signal_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('signal_item_id', sa.Integer(), nullable=False),
    sa.Column('attach_reasons', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['signal_candidates.id'], ),
    sa.ForeignKeyConstraint(['signal_item_id'], ['signal_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'signal_item_id', name='uq_candidate_signal_items')
    )
    op.create_index(op.f('ix_candidate_signal_items_candidate_id'), 'candidate_signal_items', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_signal_items_signal_item_id'), 'candidate_signal_items', ['signal_item_id'], unique=False)
    op.create_table('candidate_topic_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('matched_text', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['signal_candidates.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['monitored_topics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'topic_id', name='uq_candidate_topic_matches')
    )
    op.create_index(op.f('ix_candidate_topic_matches_candidate_id'), 'candidate_topic_matches', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_topic_matches_topic_id'), 'candidate_topic_matches', ['topic_id'], unique=False)
    op.create_table('signal_independence_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('origin_signal_item_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['signal_candidates.id'], ),
    sa.ForeignKeyConstraint(['origin_signal_item_id'], ['signal_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_independence_groups_candidate_id'), 'signal_independence_groups', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_signal_independence_groups_origin_signal_item_id'), 'signal_independence_groups', ['origin_signal_item_id'], unique=False)
    op.create_table('signal_independence_group_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('signal_item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['signal_independence_groups.id'], ),
    sa.ForeignKeyConstraint(['signal_item_id'], ['signal_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'signal_item_id', name='uq_independence_group_members')
    )
    op.create_index(op.f('ix_signal_independence_group_members_group_id'), 'signal_independence_group_members', ['group_id'], unique=False)
    op.create_index(op.f('ix_signal_independence_group_members_signal_item_id'), 'signal_independence_group_members', ['signal_item_id'], unique=False)
    # NOTE: every add_column below on a table that may already hold rows
    # (evidence, sources, source_suggestions) carries an explicit
    # server_default so SQLite can backfill existing rows in place, and runs
    # inside batch_alter_table because SQLite cannot ALTER a table to add a
    # foreign key or unique constraint directly (only batch mode's
    # copy-and-move rebuild supports that). server_default values are chosen
    # to preserve pre-merge behavior exactly: every existing source stays
    # enabled, polling/collection stays OFF, no provider identity is
    # invented. Enum columns store the Python Enum *member name* (e.g.
    # 'DOMAIN'), matching how every enum column already behaves elsewhere in
    # this schema (SQLAlchemy's default Enum persistence) -- verified
    # empirically before writing this migration, not assumed.
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origin_signal_item_id', sa.Integer(), nullable=True))
        batch_op.create_index(
            batch_op.f('ix_evidence_origin_signal_item_id'), ['origin_signal_item_id'], unique=True
        )
        batch_op.create_foreign_key(
            'fk_evidence_origin_signal_item_id_signal_items', 'signal_items', ['origin_signal_item_id'], ['id']
        )

    with op.batch_alter_table('source_suggestions', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'kind',
                sa.Enum('DOMAIN', 'HANDLE', name='sourcesuggestionkind'),
                nullable=False,
                server_default='DOMAIN',
            )
        )
        batch_op.add_column(sa.Column('platform', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('provider_key', sa.String(length=500), nullable=True))
        batch_op.add_column(
            sa.Column('independent_origin_count', sa.Integer(), nullable=False, server_default='0')
        )
        batch_op.add_column(sa.Column('inferred_reliability', sa.Float(), nullable=True))
        batch_op.create_index(batch_op.f('ix_source_suggestions_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_suggestions_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_suggestions_provider_key'), ['provider_key'], unique=False)
        batch_op.create_unique_constraint(
            'uq_source_suggestions_platform_key', ['platform', 'provider_key']
        )

    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider', sa.String(length=50), nullable=False, server_default='manual'))
        batch_op.add_column(sa.Column('provider_key', sa.String(length=500), nullable=True))
        # Existing rows had no enabled/disabled concept at all -- treat every
        # pre-merge source as enabled (unchanged effective behavior) but with
        # collection (polling_enabled) OFF, since none of them were ever
        # collected from before this merge.
        batch_op.add_column(sa.Column('enabled', sa.Boolean(), nullable=False, server_default=sa.text('1')))
        batch_op.add_column(sa.Column('polling_enabled', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('muted', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('priority', sa.Integer(), nullable=False, server_default='3'))
        batch_op.add_column(sa.Column('languages', sa.Text(), nullable=False, server_default='[]'))
        batch_op.add_column(sa.Column('expertise', sa.Text(), nullable=False, server_default='[]'))
        batch_op.add_column(sa.Column('signal_types', sa.Text(), nullable=False, server_default='[]'))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cursor', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('last_success_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_observed_item_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('error_state', sa.Text(), nullable=True))
        batch_op.add_column(
            sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP'))
        )
        batch_op.add_column(sa.Column('provider_metadata', sa.Text(), nullable=False, server_default='{}'))
        batch_op.create_index(batch_op.f('ix_sources_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_polling_enabled'), ['polling_enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_provider_key'), ['provider_key'], unique=False)
        batch_op.create_unique_constraint('uq_sources_provider_key', ['provider', 'provider_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_constraint('uq_sources_provider_key', type_='unique')
        batch_op.drop_index(batch_op.f('ix_sources_provider_key'))
        batch_op.drop_index(batch_op.f('ix_sources_provider'))
        batch_op.drop_index(batch_op.f('ix_sources_polling_enabled'))
        batch_op.drop_index(batch_op.f('ix_sources_enabled'))
        batch_op.drop_column('provider_metadata')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('error_state')
        batch_op.drop_column('last_observed_item_at')
        batch_op.drop_column('last_success_at')
        batch_op.drop_column('cursor')
        batch_op.drop_column('notes')
        batch_op.drop_column('signal_types')
        batch_op.drop_column('expertise')
        batch_op.drop_column('languages')
        batch_op.drop_column('priority')
        batch_op.drop_column('muted')
        batch_op.drop_column('polling_enabled')
        batch_op.drop_column('enabled')
        batch_op.drop_column('provider_key')
        batch_op.drop_column('provider')

    with op.batch_alter_table('source_suggestions', schema=None) as batch_op:
        batch_op.drop_constraint('uq_source_suggestions_platform_key', type_='unique')
        batch_op.drop_index(batch_op.f('ix_source_suggestions_provider_key'))
        batch_op.drop_index(batch_op.f('ix_source_suggestions_platform'))
        batch_op.drop_index(batch_op.f('ix_source_suggestions_kind'))
        batch_op.drop_column('inferred_reliability')
        batch_op.drop_column('independent_origin_count')
        batch_op.drop_column('provider_key')
        batch_op.drop_column('platform')
        batch_op.drop_column('kind')

    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_constraint('fk_evidence_origin_signal_item_id_signal_items', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_evidence_origin_signal_item_id'))
        batch_op.drop_column('origin_signal_item_id')

    op.drop_index(op.f('ix_signal_independence_group_members_signal_item_id'), table_name='signal_independence_group_members')
    op.drop_index(op.f('ix_signal_independence_group_members_group_id'), table_name='signal_independence_group_members')
    op.drop_table('signal_independence_group_members')
    op.drop_index(op.f('ix_signal_independence_groups_origin_signal_item_id'), table_name='signal_independence_groups')
    op.drop_index(op.f('ix_signal_independence_groups_candidate_id'), table_name='signal_independence_groups')
    op.drop_table('signal_independence_groups')
    op.drop_index(op.f('ix_candidate_topic_matches_topic_id'), table_name='candidate_topic_matches')
    op.drop_index(op.f('ix_candidate_topic_matches_candidate_id'), table_name='candidate_topic_matches')
    op.drop_table('candidate_topic_matches')
    op.drop_index(op.f('ix_candidate_signal_items_signal_item_id'), table_name='candidate_signal_items')
    op.drop_index(op.f('ix_candidate_signal_items_candidate_id'), table_name='candidate_signal_items')
    op.drop_table('candidate_signal_items')
    op.drop_index(op.f('ix_candidate_relationships_to_candidate_id'), table_name='candidate_relationships')
    op.drop_index(op.f('ix_candidate_relationships_from_candidate_id'), table_name='candidate_relationships')
    op.drop_table('candidate_relationships')
    op.drop_index(op.f('ix_candidate_entities_entity_id'), table_name='candidate_entities')
    op.drop_index(op.f('ix_candidate_entities_candidate_id'), table_name='candidate_entities')
    op.drop_table('candidate_entities')
    op.drop_index(op.f('ix_signal_media_signal_item_id'), table_name='signal_media')
    op.drop_index(op.f('ix_signal_media_download_state'), table_name='signal_media')
    op.drop_table('signal_media')
    op.drop_index(op.f('ix_signal_labels_signal_item_id'), table_name='signal_labels')
    op.drop_index(op.f('ix_signal_labels_label'), table_name='signal_labels')
    op.drop_table('signal_labels')
    op.drop_index(op.f('ix_signal_entity_mentions_status'), table_name='signal_entity_mentions')
    op.drop_index(op.f('ix_signal_entity_mentions_signal_item_id'), table_name='signal_entity_mentions')
    op.drop_index(op.f('ix_signal_entity_mentions_resolved_entity_id'), table_name='signal_entity_mentions')
    op.drop_index(op.f('ix_signal_entity_mentions_candidate_text'), table_name='signal_entity_mentions')
    op.drop_table('signal_entity_mentions')
    op.drop_index(op.f('ix_signal_candidates_state'), table_name='signal_candidates')
    op.drop_index(op.f('ix_signal_candidates_snoozed_until'), table_name='signal_candidates')
    op.drop_index(op.f('ix_signal_candidates_seen_at'), table_name='signal_candidates')
    op.drop_index(op.f('ix_signal_candidates_promoted_story_id'), table_name='signal_candidates')
    op.drop_index(op.f('ix_signal_candidates_primary_topic_id'), table_name='signal_candidates')
    op.drop_index(op.f('ix_signal_candidates_likely_origin_signal_item_id'), table_name='signal_candidates')
    op.drop_index(op.f('ix_signal_candidates_latest_observed_at'), table_name='signal_candidates')
    op.drop_index(op.f('ix_signal_candidates_first_observed_at'), table_name='signal_candidates')
    op.drop_index(op.f('ix_signal_candidates_fingerprint'), table_name='signal_candidates')
    op.drop_index(op.f('ix_signal_candidates_created_at'), table_name='signal_candidates')
    op.drop_index(op.f('ix_signal_candidates_attention_score'), table_name='signal_candidates')
    op.drop_table('signal_candidates')
    op.drop_index(op.f('ix_provider_runs_status'), table_name='provider_runs')
    op.drop_index(op.f('ix_provider_runs_started_at'), table_name='provider_runs')
    op.drop_index(op.f('ix_provider_runs_source_id'), table_name='provider_runs')
    op.drop_index(op.f('ix_provider_runs_provider'), table_name='provider_runs')
    op.drop_table('provider_runs')
    op.drop_index(op.f('ix_signal_items_source_id'), table_name='signal_items')
    op.drop_index(op.f('ix_signal_items_reply_to_signal_item_id'), table_name='signal_items')
    op.drop_index(op.f('ix_signal_items_quoted_signal_item_id'), table_name='signal_items')
    op.drop_index(op.f('ix_signal_items_provider'), table_name='signal_items')
    op.drop_index(op.f('ix_signal_items_processing_state'), table_name='signal_items')
    op.drop_index(op.f('ix_signal_items_posted_at'), table_name='signal_items')
    op.drop_index(op.f('ix_signal_items_origin_evidence_id'), table_name='signal_items')
    op.drop_index(op.f('ix_signal_items_external_id'), table_name='signal_items')
    op.drop_index(op.f('ix_signal_items_content_hash'), table_name='signal_items')
    op.drop_index(op.f('ix_signal_items_collected_at'), table_name='signal_items')
    op.drop_index(op.f('ix_signal_items_author_handle'), table_name='signal_items')
    op.drop_table('signal_items')
    op.drop_table('signal_collection_settings')
    op.drop_table('candidate_promotion_settings')
    op.drop_table('attention_scoring_settings')
    # ### end Alembic commands ###
